### ISSUE TITLE
Bug in math?

### ISSUE THREAD

**Issue by ecnerwala** [atcoder/ac-library#80]
https://github.com/atcoder/ac-library/blob/3cb39e9a8c7dd95eea59924019680a93465ca973/atcoder/internal_math.hpp#L59

Should this be `if (m_ <= v) v -= m_;` instead of `+=`? Or is there some other trickery happening?

**Comment by yosupo06** [comment]
We use a bit tricky technique.

```
(1)        unsigned int v = (unsigned int)(z - x * _m);
(2)        if (_m <= v) v += _m;
(3)        return v;
```

x is equal to the floor(a * b / mod) or floor(a * b / mod) + 1 (If you want to know the proof, please refer the comments of the source code). Therefore, -mod <= (z - x * _m) < mod is satisfied. As a result, (_m <= v) holds iff -mod <= (z - x * _m) < 0 is satisfied, because **v is unsigned int**.

Actually I don't remember why we used unsigned int, not int, for v.

**Comment by ecnerwala** [comment]
Ah, I see, thanks!
